Infra > Running a Validator > Operational Tasks > General Management
polkadot-developers/polkadot-docs pull request #151
Opened 2024-11-08 19:35 UTC by dawnkelly09

This PR does the following:
- takes content from PR #37 (Monitor Your Node) and PR #47 (Secure Your Node) and combines them for the General Management page for the new IA
- updates image and code snippet locations and paths

Please note:
- these screen shots are not aligned with the style guide (no browser address bar, etc.) but this is how I received them. We will have to decide if we want to remove them, keep as is, or have someone from content team capture new ones
- Grammarly was down when I was preparing to submit this. I ran Vale and my eyeballs but apologies for whatever I'm sure I missed
- I figure we can add sections to this later if we have additional content that needs to live here. Would only need to add new stuff and revamp the description and Intro

2024-11-10 17:42 UTC, CrackTheCode016 commented
Running through this, will see if I can easily get some up-to-date screenshots and terminal output

2024-11-10 19:22 UTC, CrackTheCode016 reviewed
I think this is fine to merge. There might be stuff that c omes up later, but went through the majority of the instructions: 

- ✅ Prometheus works
- ✅ Grafana works
- ✅ Alertmanager setup works (didn't test end to end, though it should be working)

The only thing left is Grafana screenshots. I have new screenshots for Grafana setup as well, if needed, or I can fire it up on our testnet to grab.

2024-11-13 02:35 UTC, themacexpert requested changes

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +There is an `Alertmanager` plugin in Grafana that can help you monitor alert information. Follow these steps to use the plugin:
```suggestion
There is an [`Alertmanager` plugin in Grafana](https://grafana.com/grafana/plugins/alertmanager/){target=\_blank} that can help you monitor alert information. Follow these steps to use the plugin: 
```

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +Given the current limitations in high-availability setups and the risks associated with double-signing, it’s recommended to run a single validator instance. Keys should be securely managed, and proce
```suggestion
Given the current limitations in high-availability setups and the risks associated with double-signing, it’s recommended to run only a single validator instance. Keys should be securely managed, and processes automated to minimize human error.
```

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +- [Certus One's Knowledge Base](https://kb.certus.one/){target=\_blank}
```suggestion
- [Certus One's Knowledge Base](https://knowledgebase.certus.com/FAQ/){target=\_blank}
```

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +    sudo systemctl daemon-reload && systemctl enable prometheus && systemctl start prometheus
```suggestion
    sudo systemctl daemon-reload && sudo systemctl enable prometheus && sudo systemctl start prometheus
```

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +    sudo systemctl daemon-reload && systemctl enable prometheus && systemctl start prometheus
You may not *need* the sudo command here but if we want to be consistent with how the commands appear in other places, we can add

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +        cd .. && rm -rf prometheus*
```suggestion
        cd .. && rm -r prometheus*
```

2024-11-13 02:35 UTC, themacexpert commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +        cd .. && rm -rf prometheus*
I don't like including force command. Dangerous if something goes wrong!

2024-11-14 19:26 UTC, dawnkelly09 reviewed
@CrackTheCode016 please see my comments on updating the Grafana instructions. THank you

2024-11-14 19:26 UTC, dawnkelly09 commented on infrastructure/running-a-validator/operational-tasks/general-management.md
> +1. **Install Grafana** - run the following commands to install Grafana:
If the instructions need updating, please make the needed changes and request a review of the grammar and formatting of the new sections. Thanks!

2024-11-14 19:49 UTC, dawnkelly09 commented
### Install and Configure Grafana section needs refactoring. @polkadot-developers/docs-content-team 
Issues:
- Bader's comment has me thinking the directions in this section are outdated/wrong (https://github.com/polkadot-developers/polkadot-docs/pull/151#discussion_r1835755678)
- I removed all of the Grafana related screenshots that came with this migrated page as none are aligned with our style guide, and they looked bad when rendered
- So...decisions need made as to what the correct directions, they need written out, and a decision needs made to either take new screenshots and upload them or rework the content so screenshots aren't used. 

Once this is all addressed, please request a new formatting/grammar update. Thanks!

2024-11-14 21:44 UTC, eshaben commented
This file is included in another PR and getting reviewed there too: https://github.com/polkadot-developers/polkadot-docs/pull/45/

2024-11-15 18:40 UTC, dawnkelly09 commented
Closing as this content is now all included in PR #45

2024-11-15 18:40 UTC, closed without merging