Add Parachain Contracts Page
polkadot-developers/polkadot-docs pull request #194
Opened 2024-11-22 00:04 UTC by themacexpert

Add Parachain Contracts Page under Develop -> Smart Contracts -> EVM -> Parachain Contracts

2024-11-22 18:50 UTC, eshaben reviewed
This is pretty text-heavy for a page in the develop section. I think at the very least we should throw in some like 'Ready to start building' call to actions that point back to developer docs of these networks

2024-11-22 22:56 UTC, albertov19 requested changes
I think overall I would like to see a bit more code, like for example how to get started with Remix, Hardhat and Foundry for EVM enabled Polkadot parachains? Super simple code snippets or something like that.

Wdyt?

2024-11-22 22:56 UTC, albertov19 commented on develop/smart-contracts/evm/parachain-contracts.md
> +### Manta
Their polkadot implementation is not eVM I would remove

2024-11-22 22:56 UTC, albertov19 commented on develop/smart-contracts/evm/parachain-contracts.md
> +## Why Adopt the EVM as a Polkadot Parachain?
I would merge this a bit with "## EVM + The Power of Polkadot"

Moreover, I think this section needs a bit more images or a mermaid diagram. Maybe the classic "User -> Ethereum API (Precompiles) -> Subtrate API?" Wdyt?

2024-11-23 03:06 UTC, themacexpert commented
@albertov19 Added Hardhat, and read contract state section, and Mermaid diagrams and cleaned up some other things! 
If you think we need Foundry I can add that too.

2024-11-23 12:51 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +[Astar](https://astar.network/){target=_blank} emerged as a key smart contract platform on Polkadot, distinguished by its unique multiple virtual machine approach that supports both EVM and WebAssemb
```suggestion
[Astar](https://astar.network/){target=\_blank} emerged as a key smart contract platform on Polkadot, distinguished by its unique multiple virtual machine approach that supports both EVM and WebAssembly (Wasm) smart contracts. This dual VM support allows developers to choose their preferred programming environment while maintaining full Ethereum compatibility. The platform's [runtime](https://github.com/AstarNetwork/Astar){target=\_blank} is built on Substrate using FRAME, incorporating crucial components from Polkadot-SDK alongside custom-built modules for handling its unique features.
```

2024-11-23 12:52 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +Additionally, Moonbeam is a hub for interoperability and cross-chain connected contracts. Moonbeam has a variety of integrations with GMP (general message passing) providers, including [Wormhole](htt
```suggestion
Additionally, Moonbeam is a hub for interoperability and cross-chain connected contracts. Moonbeam has a variety of integrations with GMP (general message passing) providers, including [Wormhole](https://wormhole.com/){target=\_blank}, [LayerZero](https://layerzero.network/){target=\_blank}, [Axelar](https://www.axelar.network/){target=\_blank}, and more. These integrations make it easy for developers to build cross-chain contracts on Moonbeam, and they also play an integral role in connecting the entire Polkadot ecosystem with other blockchains. Innovations like [Moonbeam Routed Liquidity](https://docs.moonbeam.network/builders/interoperability/mrl/){target=\_blank}, or MRL, enable users to bridge funds between chains like Ethereum and parachains like HydraDX. Through [XCM](/develop/interoperability/intro-to-xcm/){target=\_blank}, other parachains can connect to Moonbeam and access its established bridge connections to Ethereum and other networks, eliminating the need for each parachain to build and maintain their own bridges.
```

2024-11-23 12:52 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +Acala supports a comprehensive DeFi ecosystem including a decentralized stablecoin (aUSD) and a liquid staking derivative for DOT. The platform's EVM+ innovations extend beyond standard Ethereum comp
```suggestion
Acala supports a comprehensive DeFi ecosystem including a decentralized stablecoin (aUSD) and a liquid staking derivative for DOT. The platform's EVM+ innovations extend beyond standard Ethereum compatibility by enabling direct interaction between EVM smart contracts and Substrate pallets, facilitating advanced cross-chain DeFi operations through [XCM](/develop/interoperability/intro-to-xcm/){target=\_blank}, and providing built-in oracle integrations. These enhancements make it possible for DeFi protocols to achieve functionality that would be prohibitively expensive or technically infeasible on traditional EVM chains.
```

2024-11-23 12:53 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +[Hardhat](https://hardhat.org){target=_blank} is an Ethereum development environment that makes it easy to deploy smart contracts on EVM-compatible blockchain networks. This guide will show you how t
```suggestion
[Hardhat](https://hardhat.org){target=\_blank} is an Ethereum development environment that makes it easy to deploy smart contracts on EVM-compatible blockchain networks. This guide will show you how to compile, deploy, and interact with a simple smart contract on Astar, Moonbeam, and Acala. Feel free to pick your network of choice and follow along!
```

2024-11-23 12:53 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +	You'll need to have [MetaMask installed](https://metamask.io/){target=_blank} and connected to [Moonbase Alpha](https://chainlist.org/chain/1287){target=_blank} and an account with Moonbase Alpha to
```suggestion
	You'll need to have [MetaMask installed](https://metamask.io/){target=\_blank} and connected to [Moonbase Alpha](https://chainlist.org/chain/1287){target=\_blank} and an account with Moonbase Alpha tokens. You can get them from [the Moonbase Alpha faucet](https://faucet.moonbeam.network){target=_blank}.
```

2024-11-23 12:53 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +	You'll need to have [MetaMask installed](https://metamask.io/){target=_blank} and connected to [Acala Testnet](https://chainlist.org/chain/595){target=_blank} and an account with Acala testnet token
```suggestion
	You'll need to have [MetaMask installed](https://metamask.io/){target=\_blank} and connected to [Acala Testnet](https://chainlist.org/chain/595){target=\_blank} and an account with Acala testnet tokens. You can get them from [the Acala testnet faucet](https://discord.gg/5JJgXKSznc){target=\_blank}.
```

2024-11-23 12:55 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +What makes this demo particularly powerful is that all three chains—Astar, Moonbeam, and Acala—share EVM compatibility. This means we can use a single, unified script to query token balances across a
We avoid using first person pronouns like "we" or "ours"

2024-11-23 12:55 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +    | Faucet Link | [Faucet - Astar Docs](https://docs.astar.network/docs/build/environment/faucet/){target=_blank} |
```suggestion
    | Block Explorer | [Shibuya Blockscout](https://blockscout.com/shibuya){target=\_blank} |
    | Faucet Link | [Faucet - Astar Docs](https://docs.astar.network/docs/build/environment/faucet/){target=\_blank} |
```

2024-11-23 12:56 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +    | Faucet Link | [Moonbase Faucet](https://faucet.moonbeam.network){target=_blank} |
```suggestion
    | Block Explorer | [Moonbase Alpha Moonscan](https://moonbase.moonscan.io/){target=\_blank} |
    | Faucet Link | [Moonbase Faucet](https://faucet.moonbeam.network){target=\_blank} |
```

2024-11-23 12:56 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +    | Faucet Link | [Mandala Faucet](https://discord.gg/5JJgXKSznc){target=_blank} |
```suggestion
    | Block Explorer | [Mandala Blockscout](https://blockscout.mandala.aca-staging.network){target=\_blank} |
    | Faucet Link | [Mandala Faucet](https://discord.gg/5JJgXKSznc){target=\_blank} |
```

2024-11-23 12:56 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +    - [Build EVM Smart Contracts on Astar](https://docs.astar.network/docs/build/EVM/){target=_blank}
```suggestion
    - [Astar Docs](https://docs.astar.network/){target=\_blank}
    - [Astar Network Endpoints](https://docs.astar.network/docs/build/environment/endpoints/){target=\_blank}
    - [Build EVM Smart Contracts on Astar](https://docs.astar.network/docs/build/EVM/){target=\_blank}
```

2024-11-23 12:57 UTC, nhussein11 commented on develop/smart-contracts/evm/parachain-contracts.md
> +    - [About the Acala Network](https://wiki.acala.network/learn/acala-introduction){target=_blank}
```suggestion
=== "Astar"
    - [Astar Docs](https://docs.astar.network/){target=\_blank}
    - [Astar Network Endpoints](https://docs.astar.network/docs/build/environment/endpoints/){target=\_blank}
    - [Build EVM Smart Contracts on Astar](https://docs.astar.network/docs/build/EVM/){target=\_blank}

=== "Moonbeam"
    - [Moonbeam Docs](https://docs.moonbeam.network/){target=\_blank}
    - [Moonbeam Network Endpoints](https://docs.moonbeam.network/builders/get-started/endpoints/){target=\_blank}
    - [Get Started Building on Moonbeam](https://docs.moonbeam.network/builders/get-started/){target=\_blank}

=== "Acala"
    - [Acala Docs](https://evmdocs.acala.network/){target=\_blank}
    - [Acala Network Endpoints](https://wiki.acala.network/integrate/acala/endpoints){target=\_blank}
    - [About the Acala Network](https://wiki.acala.network/learn/acala-introduction){target=\_blank}
```

2024-11-23 12:58 UTC, nhussein11 reviewed
Some formatting comments, the rest is good to go IMO

2024-11-23 15:28 UTC, albertov19 requested changes
Looking good! Left some mermaid comments and also check the structure of other pages to ensure that it is consistent. Please discuss with nico and Luca

2024-11-23 20:58 UTC, nhussein11 approved these changes
LGTM! 🚀

2024-11-23 21:01 UTC, nhussein11 commented
> Looking good! Left some mermaid comments and also check the structure of other pages to ensure that it is consistent. Please discuss with nico and Luca

We can merge this PR and then do a separate PR to align the 3 smart contracts pages with a similar structure. WDYT @themacexpert @albertov19 ?

2024-11-23 22:27 UTC, themacexpert commented
> > Looking good! Left some mermaid comments and also check the structure of other pages to ensure that it is consistent. Please discuss with nico and Luca
> 
> We can merge this PR and then do a separate PR to align the 3 smart contracts pages with a similar structure. WDYT @themacexpert @albertov19 ?

Sure! Works for me

2024-11-23 22:33 UTC, albertov19 approved these changes

2024-11-23 22:57 UTC, eshaben reviewed
Noticed some minor formatting things

2024-11-23 22:57 UTC, eshaben commented on .snippets/code/develop/smart-contracts/parachain-contracts/check-token-supply.js
> +const NETWORK_CONFIGS = {
```suggestion
const networkConfigs = {
```

2024-11-23 22:57 UTC, eshaben commented on .snippets/code/develop/smart-contracts/parachain-contracts/check-token-supply.js
> +const ERC20_ABI = [
```suggestion
const erc20ABI = [
```

2024-11-23 22:57 UTC, eshaben commented on .snippets/code/develop/smart-contracts/parachain-contracts/check-token-supply.js
> +    const networkConfig = NETWORK_CONFIGS[networkKey];
```suggestion
    const networkConfig = networkConfigs[networkKey];
```

2024-11-23 22:57 UTC, eshaben commented on .snippets/code/develop/smart-contracts/parachain-contracts/check-token-supply.js
> +    const contract = new ethers.Contract(tokenAddress, ERC20_ABI, provider);
```suggestion
    const contract = new ethers.Contract(tokenAddress, erc20ABI, provider);
```

2024-11-23 22:57 UTC, eshaben commented on .snippets/code/develop/smart-contracts/parachain-contracts/check-token-supply.js
> +    moonbeam: "0x931715FEE2d06333043d11F658C8CE934aC61D0c", // Wormhole USDC
This file doesn't look like it was formatted. It has double quotes instead of single

2024-11-23 22:57 UTC, eshaben commented on develop/smart-contracts/evm/parachain-contracts.md
> +| Public WSS URLs | <pre>wss://evm.shibuya.astar.network</pre> |
```suggestion
| Public RPC URLs | <pre>```https://evm.shibuya.astar.network```</pre> |
| Public WSS URLs | <pre>```wss://evm.shibuya.astar.network```</pre> |
```

2024-11-23 22:57 UTC, eshaben commented on develop/smart-contracts/evm/parachain-contracts.md
> +| Public WSS URLs | <pre>wss://wss.api.moonbase.moonbeam.network</pre> |
```suggestion
| Public RPC URLs | <pre>```https://rpc.api.moonbase.moonbeam.network```</pre> |
| Public WSS URLs | <pre>```wss://wss.api.moonbase.moonbeam.network```</pre> |
```

2024-11-23 22:57 UTC, eshaben commented on develop/smart-contracts/evm/parachain-contracts.md
> +| Public WSS URLs | <pre>wss://tc7-eth.aca-dev.network</pre> |
```suggestion
| Public RPC URLs | <pre>```https://eth-rpc-tc9.aca-staging.network```</pre> |
| Public WSS URLs | <pre>```wss://tc7-eth.aca-dev.network```</pre> |
```

2024-11-23 22:57 UTC, eshaben commented on develop/smart-contracts/evm/parachain-contracts.md
> +| Public WSS URLs | <pre>wss://evm.shibuya.astar.network</pre> |
Ideally these tables would be formatted, but not a big deal

2024-11-24 13:41 UTC, 0xLucca approved these changes
LGTM!

2024-11-24 13:41 UTC, merged