Create Tutorial Index Pages
polkadot-developers/polkadot-docs pull request #210
Opened 2024-11-24 07:11 UTC by themacexpert

Creates Index pages for the Tutorial section.

2024-11-24 13:45 UTC, 0xLucca approved these changes
LGTM!

2024-11-24 14:43 UTC, albertov19 commented
@themacexpert check the latest changes to the Tutorials section :) https://github.com/polkadot-developers/polkadot-docs/pull/205/commits/fc8524f67389ab1df52052eb6322fefc41a55460

2024-11-24 18:26 UTC, nhussein11 commented on tutorials/polkadot-sdk/testing/index.md
> +Unlike most blockchains, Polkadot offers specialized tools that make it simple to create realistic testing environments, particularly for cross-chain interactions. These purpose-built tools enable de
maybe this is a bit politically correct haha, wdyt?:
```suggestion
Polkadot offers specialized tools that make it simple to create realistic testing environments, particularly for cross-chain interactions. These purpose-built tools enable developers to quickly spin up test networks that accurately simulate real-world scenarios.
```

2024-11-24 18:26 UTC, nhussein11 approved these changes
LGTM!

2024-11-24 22:12 UTC, albertov19 requested changes
I think this is a good start but I would like to see a bit more story telling in the index pages similar to what we have in the Infrastructure section 😄 

Highlight a few tutorials and then do the " in this section"

2024-11-25 03:11 UTC, themacexpert commented
This is ready for review again :)

2024-11-25 11:22 UTC, nhussein11 commented on tutorials/index.md
> +      <p class="description">Learn to compile and launch a local blockchain node using Polkadot SDK. Launch, run, and interact with a pre-configured node template.</p>
```suggestion
      <p class="description">Learn how to compile and launch a local blockchain node using Polkadot SDK. Launch, run, and interact with a pre-configured node template.</p>
```

2024-11-25 11:24 UTC, nhussein11 commented on tutorials/interoperability/index.md
> +Bridges extend interoperability beyond the Polkadot network by connecting to external blockchains. This enables the integration of external assets, unlocking liquidity and enhancing the functionality
```suggestion
Bridges extend interoperability beyond the Polkadot network by connecting to external blockchains. This enables the integration of external assets, unlocking liquidity and enhancing the functionality of Polkadot SDK-based applications.
```

2024-11-25 11:29 UTC, nhussein11 commented on tutorials/polkadot-sdk/index.md
> +      <p class="description">Install everything you need to begin working with Substrated-based blockchains and the Polkadot SDK.</p>
```suggestion
      <p class="description">Install everything you need to begin working with Polkadot SDK-based blockchains.</p>
```

2024-11-25 11:31 UTC, nhussein11 commented on tutorials/polkadot-sdk/system-chains/asset-hub/index.md
> +- **[Convert Assets](/tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion/){target=\_blank}** - Use Asset Hub's AMM functionality to swap between different assets, provide liquidity to po
```suggestion
- **[Register a Local Asset](/tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset/){target=\_blank}** - create and configure new assets directly on Asset Hub with custom parameters like metadata and minimum balances
- **[Register a Foreign Asset](/tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset/){target=\_blank}** - connect assets from other parachains to Asset Hub using XCM for cross-chain functionality 
- **[Convert Assets](/tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion/){target=\_blank}** - use Asset Hub's AMM functionality to swap between different assets, provide liquidity to pools, and manage LP tokens
```

2024-11-25 11:32 UTC, nhussein11 commented on tutorials/polkadot-sdk/system-chains/index.md
> +- **[Convert Assets](/tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion/){target=\_blank}** - Use Asset Hub's AMM functionality to swap between different assets, provide liquidity to po
```suggestion
- **[Register a Local Asset](/tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset/){target=\_blank}** - create and configure new assets directly on Asset Hub with custom parameters like metadata and minimum balances
- **[Register a Foreign Asset](/tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset/){target=\_blank}** - connect assets from other parachains to Asset Hub using XCM for cross-chain functionality 
- **[Convert Assets](/tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion/){target=\_blank}** - use Asset Hub's AMM functionality to swap between different assets, provide liquidity to pools, and manage LP tokens
```

2024-11-25 11:33 UTC, nhussein11 commented on tutorials/polkadot-sdk/testing/index.md
> +- **[Fork a Chain with Chopsticks](/tutorials/polkadot-sdk/testing/fork-live-chains/){target=\_blank}** - Create local forks of live chains to test functionality, replay blocks, and simulate cross-ch
```suggestion
- **[Spawn a Basic Chain with Zombienet](/tutorials/polkadot-sdk/testing/spawn-basic-chain/){target=\_blank}** - deploy temporary networks for testing, with customizable configurations and monitoring capabilities
- **[Fork a Chain with Chopsticks](/tutorials/polkadot-sdk/testing/fork-live-chains/){target=\_blank}** - create local forks of live chains to test functionality, replay blocks, and simulate cross-chain messaging
```

2024-11-25 11:34 UTC, nhussein11 commented on tutorials/interoperability/index.md
> +- **[Opening HRMP Channels with System Parachains](/tutorials/interoperability/xcm-channels/para-to-system/){target=\_blank}** - Establish communication channels with system parachains using optimize
```suggestion
- **[Opening HRMP Channels Between Parachains](/tutorials/interoperability/xcm-channels/para-to-para/){target=\_blank}** - set up uni- and bidirectional messaging channels between parachains
- **[Opening HRMP Channels with System Parachains](/tutorials/interoperability/xcm-channels/para-to-system/){target=\_blank}** - establish communication channels with system parachains using optimized XCM messages
```

2024-11-25 11:34 UTC, nhussein11 commented on tutorials/polkadot-sdk/parachains/index.md
> +- **[Acquire a TestNet Slot](/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/){target=\_blank}** - Deploy your parachain to the Paseo TestNet
```suggestion
- **[Prepare a Relay Chain](/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-relay-chain/){target=\_blank}** - set up a local relay chain for testing
- **[Prepare a Parachain](/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-parachain/){target=\_blank}** - configure and connect your parachain to the relay chain
- **[Acquire a TestNet Slot](/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/){target=\_blank}** - deploy your parachain to the Paseo TestNet
```

2024-11-25 11:35 UTC, nhussein11 commented on tutorials/polkadot-sdk/parachains/local-chain/index.md
> +- **[Upgrade a Running Network](/tutorials/polkadot-sdk/parachains/local-chain/upgrade-a-running-network/){target=\_blank}** - Perform forkless runtime upgrades to add features and modify parameters
```suggestion
- **[Launch a Local Solochain](/tutorials/polkadot-sdk/parachains/local-chain/launch-a-local-solochain/){target=\_blank}** - compile and launch your first blockchain node using the Polkadot SDK Solochain Template. Learn to run a standalone node and interact with it through the Polkadot.js Apps interface

- **[Connect Predefined Accounts](/tutorials/polkadot-sdk/parachains/local-chain/connect-multiple-nodes/){target=\_blank}** - create a multi-node network environment using predefined accounts (Alice and Bob). Learn how to connect peers and verify block production in a controlled setting

- **[Spin Your Own Nodes](/tutorials/polkadot-sdk/parachains/local-chain/spin-your-nodes/){target=\_blank}** - set up a private blockchain network with your own authorized validators. Generate keys, create custom chain specifications, and manage node authorization using Aura consensus

- **[Upgrade a Running Network](/tutorials/polkadot-sdk/parachains/local-chain/upgrade-a-running-network/){target=\_blank}** - perform forkless runtime upgrades to add features and modify parameters without disrupting network operations. Learn to add pallets and update runtime configuration
```

2024-11-25 13:48 UTC, dawnkelly09 commented
Implemented Nico's suggestions and updated one page that had the wrong title attached but the rest was ok. May still need some storytelling, etc.

2024-11-25 14:55 UTC, albertov19 requested changes
generally speaking I think we should include more links here and there to tutorials that are being covered.

but it is looking better

2024-11-25 20:48 UTC, eshaben approved these changes

2024-11-25 22:30 UTC, albertov19 approved these changes
LGTM!!!!! 🚢

2024-11-25 22:31 UTC, merged