add pages for legal policies and info
polkadot-developers/polkadot-docs pull request #255
Opened 2024-12-13 16:17 UTC by eshaben

Add placeholder pages for the legal info

2024-12-16 12:22 UTC, 0xLucca approved these changes
LGTM!

2024-12-17 11:01 UTC, albertov19 approved these changes
LGTM

2024-12-17 11:03 UTC, albertov19 requested changes
Fixed the URLs now that it is merged in mkdocs

2024-12-17 11:03 UTC, albertov19 commented on cookie-policy.md
> +--8<-- 'https://raw.githubusercontent.com/papermoonio/polkadot-mkdocs/refs/heads/main/legal/policies/cookie-policy.md'
```suggestion
--8<-- 'https://raw.githubusercontent.com/papermoonio/polkadot-mkdocs/refs/heads/main/policies/cookie-policy.md'
```

2024-12-17 11:03 UTC, albertov19 commented on privacy-policy.md
> +--8<-- 'https://raw.githubusercontent.com/papermoonio/polkadot-mkdocs/refs/heads/main/legal/policies/privacy-policy.md'
```suggestion
--8<-- 'https://raw.githubusercontent.com/papermoonio/polkadot-mkdocs/refs/heads/main/policies/privacy-policy.md'
```

2024-12-17 11:03 UTC, albertov19 commented on terms-of-use.md
> +--8<-- 'https://raw.githubusercontent.com/papermoonio/polkadot-mkdocs/refs/heads/main/legal/policies/terms-of-use.md'
```suggestion
--8<-- 'https://raw.githubusercontent.com/papermoonio/polkadot-mkdocs/refs/heads/main/policies/terms-of-use.md'
```

2024-12-17 11:41 UTC, 0xLucca approved these changes

2024-12-17 11:57 UTC, albertov19 approved these changes

2024-12-17 11:57 UTC, merged