Create mermaid diagram for FRAME section
polkadot-developers/polkadot-docs pull request #280
Opened 2024-12-19 17:53 UTC by dawnkelly09

This PR adds a first draft mermaid diagram for the FRAME section. 

@nhussein11 can you improve this one as well? I'm not sure how I feel about this current version.

2024-12-26 17:07 UTC, CrackTheCode016 reviewed
Looks overall correct to me, @kianenigma would be the best one to ask here.

2025-01-08 08:37 UTC, kianenigma commented on develop/parachains/intro-polkadot-sdk.md
> +    subgraph sg1[Client/Host]
please use this as an oppurtunity and:

1. Add somewhere in glossary that in substrate, "Client", "Node" and "Host" are the same.
2. For consistency, we always prefer to say "Node", so update all instances to use this keyword foremost.

2025-01-08 08:40 UTC, kianenigma commented on develop/parachains/intro-polkadot-sdk.md
> +        H[Executive]
have you explained "executive" anywhere? I worry this might be some low level of detail that the old docs had and we are mistakenly copying it. 

For any new keyword added, ask yourself, does the reader already know what this is? if yes, good. If no, either remove, or add a link to where it is explained. 

Executive is a fairly low level detail of FRAME. 

I have some better resources for you to create a more informed version of this diagram: 

- https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/polkadot_sdk/index.html#summary
- https://polkadot-blockchain-academy.github.io/pba-content/singapore-2024/syllabus/6-Polkadot-SDK/FRAME/1-Intro_to_FRAME/Intro_to_FRAME-slides.html#/5

2025-01-08 08:40 UTC, kianenigma requested changes
We can do slightly better, let's iterate one more time based on the resources I provided, thanks!

2025-01-08 21:43 UTC, dawnkelly09 commented on develop/parachains/intro-polkadot-sdk.md
> +    subgraph sg1[Client/Host]
I've opened a ticket to address this feedback. Thank you for the clarification!

2025-01-15 15:18 UTC, dawnkelly09 commented
@nhussein11 Updated this so it's the diagram showing the larger group of pallets and then the selected group to create a runtime. Definitely needs some styling if you can help with that. 

@0xLucca  mentioned: "This runtime could be link to the solochain-template as it mimics the pallets included in that runtime" but, I'm not sure I can make the mermaid clickable? I added a "tip" admonition but feel free to change things if you know how to link from the diagram or think of a better way to share that info. Thank you for your help!

2025-01-17 15:25 UTC, UtkarshBhardwaj007 commented on develop/parachains/intro-polkadot-sdk.md
> +
Looks okay but it is missing the configurable aspect of pallets. Maybe something like: 

```mermaid
graph TD
    subgraph "FRAME Pallets"
        B[Balances Pallet]
        S[Staking Pallet]
        G[Governance Pallet]
        T[Treasury Pallet]
        C[Contracts Pallet]
        style B fill:#99ccff,stroke:#333,color:#000
        style S fill:#99ccff,stroke:#333,color:#000
        style G fill:#99ccff,stroke:#333,color:#000
        style T fill:#99ccff,stroke:#333,color:#000
        style C fill:#99ccff,stroke:#333,color:#000
    end

    subgraph "Custom Runtime"
        R[Your Runtime] --> MB[Modified Balances]
        R --> MS[Modified Staking]
        R --> CP[Custom Pallet]
        
        MB -.-> B
        MS -.-> S
        
        style R fill:#ff9966,stroke:#333,stroke-width:2px,color:#000
        style MB fill:#cce6ff,stroke:#333,color:#000
        style MS fill:#cce6ff,stroke:#333,color:#000
        style CP fill:#ffcccc,stroke:#333,color:#000
    end

    subgraph "Configuration"
        MB --> C1["Custom Config:
        - Modified weights
        - Custom parameters
        - Added features"]
        
        MS --> C2["Custom Config:
        - Modified rewards
        - Custom rules
        - Added validations"]
        
        style C1 fill:#f2f2f2,stroke:#333,color:#000
        style C2 fill:#f2f2f2,stroke:#333,color:#000
    end
```

2025-01-20 13:35 UTC, nhussein11 commented on develop/parachains/intro-polkadot-sdk.md
> +
@UtkarshBhardwaj007 I like this! Maybe we can add this diagram as a complement to the one we have now and follow up on that in a new PR. Since this is the introduction to the Polkadot SDK, I think explaining it at a high level is a good idea, especially since the diagrams are easy to understand and digest for those onboarding to Polkadot.

Long story short, I'd suggest we use your diagram in another section (maybe on the same page but below) and keep the diagram as simple as possible at first, then get into more technical details as the documentation progresses. WDYT?

2025-01-21 13:10 UTC, nhussein11 commented on develop/parachains/intro-polkadot-sdk.md
> +
Perfect, we talked with Luca and see that maybe we can do something like this to showcase the customizable aspect:

![image](https://github.com/user-attachments/assets/89454854-b5fe-4fa3-89ac-09421b8005e9)

@UtkarshBhardwaj007  WDYT?

The code of the diagram would be like:
```
graph LR
    subgraph SP["<b style='font-size:18px;'>Runtime</b>"]
        direction LR
        Timestamp ~~~ Aura ~~~ GRANDPA
        Balances ~~~ TransactionPayment ~~~ Sudo
        subgraph Timestamp["Timestamp"]
            SS1[Custom Config]
        end
        subgraph Aura["Aura"]
            SS2[Custom Config]
        end
        subgraph GRANDPA["GRANDPA"]
            SS3[Custom Config]
        end
        subgraph Balances["Balances"]
            SS4[Custom Config]
        end
        subgraph TransactionPayment["Transaction Payment"]
            SS5[Custom Config]
        end
        subgraph Sudo["Sudo"]
            SS6[Custom Config]
        end
        style Timestamp stroke:#FF69B4
        style Aura stroke:#FF69B4
        style GRANDPA stroke:#FF69B4
        style Balances stroke:#FF69B4
        style TransactionPayment stroke:#FF69B4
        style Sudo stroke:#FF69B4
        style SS1 stroke-dasharray: 5
        style SS2 stroke-dasharray: 5
        style SS3 stroke-dasharray: 5
        style SS4 stroke-dasharray: 5
        style SS5 stroke-dasharray: 5
        style SS6 stroke-dasharray: 5

    end
    subgraph AP["<b style='font-size:18px;'>FRAME Pallets</b>"]
        direction LR
        A1[Aura]~~~A2[BABE]~~~A3[GRANDPA]~~~A4[Transaction\nPayment]
        B1[Identity]~~~B2[Balances]~~~B3[Sudo]~~~B4[EVM]
        C1[Timestamp]~~~C2[Assets]~~~C3[Contracts]~~~C4[and more...]
    end
    AP --> SP
```

2025-01-21 14:56 UTC, UtkarshBhardwaj007 commented on develop/parachains/intro-polkadot-sdk.md
> +
LGTM. Although the colours from the code snippet look a bit different from the image you shared (See below).

```mermaid
graph LR
    subgraph SP["<b style='font-size:18px;'>Runtime</b>"]
        direction LR
        Timestamp ~~~ Aura ~~~ GRANDPA
        Balances ~~~ TransactionPayment ~~~ Sudo
        subgraph Timestamp["Timestamp"]
            SS1[Custom Config]
        end
        subgraph Aura["Aura"]
            SS2[Custom Config]
        end
        subgraph GRANDPA["GRANDPA"]
            SS3[Custom Config]
        end
        subgraph Balances["Balances"]
            SS4[Custom Config]
        end
        subgraph TransactionPayment["Transaction Payment"]
            SS5[Custom Config]
        end
        subgraph Sudo["Sudo"]
            SS6[Custom Config]
        end
        style Timestamp stroke:#FF69B4
        style Aura stroke:#FF69B4
        style GRANDPA stroke:#FF69B4
        style Balances stroke:#FF69B4
        style TransactionPayment stroke:#FF69B4
        style Sudo stroke:#FF69B4
        style SS1 stroke-dasharray: 5
        style SS2 stroke-dasharray: 5
        style SS3 stroke-dasharray: 5
        style SS4 stroke-dasharray: 5
        style SS5 stroke-dasharray: 5
        style SS6 stroke-dasharray: 5

    end
    subgraph AP["<b style='font-size:18px;'>FRAME Pallets</b>"]
        direction LR
        A1[Aura]~~~A2[BABE]~~~A3[GRANDPA]~~~A4[Transaction\nPayment]
        B1[Identity]~~~B2[Balances]~~~B3[Sudo]~~~B4[EVM]
        C1[Timestamp]~~~C2[Assets]~~~C3[Contracts]~~~C4[and more...]
    end
    AP --> SP
```

2025-01-21 15:08 UTC, nhussein11 commented on develop/parachains/intro-polkadot-sdk.md
> +
Yeah, that's likely because the gh processor doesn't have the same css settings as we do in the `polkadot-mkdocs` repo. If you copy and paste the diagram into the `develop/parachains/intro-polkadot-sdk.md` page, you should see all the styles applied.

2025-01-23 03:45 UTC, eshaben approved these changes
LGTM

2025-01-23 13:14 UTC, UtkarshBhardwaj007 approved these changes
LGTM

2025-01-23 16:33 UTC, albertov19 commented
Mergin per @kianenigma suggestion

2025-01-23 16:33 UTC, merged